TIMEOUT_VAL = 0.2

GAME_SCREEN_WIDTH = 120
GAME_SCREEN_HEIGHT = 30
GAME_HORIZONTAL_BOUNDARY = 2
GAME_VERTCIAL_BOUNDARY = 1

KING_STARTING_X = 20
KING_STARTING_Y = 15
KING_HEALTH = 100
KING_SPEED = 1
KING_ATTACK = 10

TOWN_X_POSITION = 50
TOWN_Y_POSITION = 10
TOWN_HEALTH = 200

NUMBER_HUTS = 6
NUMBER_HUTS_IN_ROW = int(NUMBER_HUTS/2)
HUT_STARTING1 = 40
HUT_STARTING2 = 70
HUT_STARTINGY = 6
HUT_HEALTH = 48

WALL_STARTING1X = 35
WALL_STARTING2X = 80
WALL_STARTING1Y = 4
WALL_STARTING2Y = 23
NUMBER_WALLS_X = WALL_STARTING2X - WALL_STARTING1X
NUMBER_WALLS_Y = WALL_STARTING2Y - WALL_STARTING1Y + 1
WALL_HEALTH = 14

CANNON_1X = 57
CANNON_2X = 57
CANNON_1Y = 6
CANNON_2Y = 18
CANNON_HEALTH = 100
CANNON_DAMAGE = 1
CANNON_RANGE = 25

BARBARIAN_HEALTH = 10
BARBARIAN_SPEED = 1
BARBARIAN_ATTACK = 2
