GAME_SCREEN_WIDTH = 160
GAME_SCREEN_HEIGHT = 40
GAME_HORIZONTAL_BOUNDARY = 2
GAME_VERTCIAL_BOUNDARY = 1

KING_STARTING_X = 63
KING_STARTING_Y = 20
KING_HEALTH = 100
KING_SPEED = 1
KING_ATTACK = 3

TOWN_X_POSITION = 70
TOWN_Y_POSITION = 15
TOWN_HEALTH = 100

NUMBER_HUTS = 6
NUMBER_HUTS_IN_ROW = int(NUMBER_HUTS/2)
HUT_STARTING1 = 60
HUT_STARTING2 = 90

WALL_STARTING1X = 55
WALL_STARTING2X = 100
WALL_STARTING1Y = 8
WALL_STARTING2Y = 27
NUMBER_WALLS_X = WALL_STARTING2X - WALL_STARTING1X
NUMBER_WALLS_Y = WALL_STARTING2Y - WALL_STARTING1Y + 1

CANNON_1X = 74
CANNON_2X = 74
CANNON_1Y = 10
CANNON_2Y = 22
CANNON_HEALTH = 100
CANNON_DAMAGE = 4
CANNON_RANGE = 5