from tkinter.tix import BALLOON


MAX_BARBARIANS = 6
MAX_ARCHERS = 6
MAX_BALLOONS = 3

MAX_SPELLS = 2

TIMEOUT_VAL = 0.1

GAME_SCREEN_WIDTH = 120
GAME_SCREEN_HEIGHT = 30
GAME_HORIZONTAL_BOUNDARY = 2
GAME_VERTCIAL_BOUNDARY = 1

KING_STARTING_X = 20
KING_STARTING_Y = 15
KING_HEALTH = 100
KING_SPEED = 1
KING_ATTACK = 10

QUEEN_STARTING_X = KING_STARTING_X + 5
QUEEN_STARTING_Y = KING_STARTING_Y + 10
QUEEN_ATTACK = KING_ATTACK - 5
QUEEN_HEALTH = KING_HEALTH
QUEEN_SPEED = KING_SPEED

TOWN_X_POSITION = 50
TOWN_Y_POSITION = 10
TOWN_HEALTH = 200

NUMBER_HUTS = 6
NUMBER_HUTS_IN_ROW = int(NUMBER_HUTS/2)
HUT_STARTING1 = 40
HUT_STARTING2 = 70
HUT_STARTINGY = 6
HUT_HEALTH = 48

WALL_STARTING1X = 35
WALL_STARTING2X = 80
WALL_STARTING1Y = 4
WALL_STARTING2Y = 23
NUMBER_WALLS_X = WALL_STARTING2X - WALL_STARTING1X
NUMBER_WALLS_Y = WALL_STARTING2Y - WALL_STARTING1Y + 1
WALL_HEALTH = 14

CANNON_1X = 61
CANNON_2X = 52
CANNON_1Y = 6
CANNON_2Y = 18
CANNON_HEALTH = 100
CANNON_DAMAGE = 1
CANNON_RANGE = 25


TOWER_HEALTH = 100
TOWER_DAMAGE = 1
TOWER_RANGE = 25
TOWER_1X = 52
TOWER_2X = 61
TOWER_1Y = 6
TOWER_2Y = 18

BARBARIAN_HEALTH = 10
BARBARIAN_SPEED = 1
BARBARIAN_ATTACK = 2

ARCHER_HEALTH = BARBARIAN_HEALTH/2
ARCHER_SPEED = BARBARIAN_SPEED*2
ARCHER_ATTACK = BARBARIAN_ATTACK/2
ARCHER_RANGE = CANNON_RANGE + 5

BALLOON_HEALTH = BARBARIAN_HEALTH
BALLOON_ATTACK = BARBARIAN_ATTACK*2
BALLOON_SPEED = BARBARIAN_SPEED*2

AXE_RANGE = 10